# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'theQRL' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'theQRL', :path => '.'
  # Pods for theQRL
  # pod 'NSHash', '~> 1.2.0'
  # target 'theQRL-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end
  #pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  #pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  #pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  #pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  pod 'react-native-shimmer', :path => '../node_modules/react-native-shimmer'


  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  # target 'theQRLTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end



end

# target 'theQRL-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for theQRL-tvOS

#   target 'theQRL-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
