# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'theQRL' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'theQRL', :path => '.'
  # Pods for theQRL

  # target 'theQRL-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end
  #
  # target 'theQRLTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

# target 'theQRL-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for theQRL-tvOS

#   target 'theQRL-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
