/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.qrl.BlockMetaData');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qrl.BlockMetaData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.qrl.BlockMetaData.repeatedFields_, null);
};
goog.inherits(proto.qrl.BlockMetaData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qrl.BlockMetaData.displayName = 'proto.qrl.BlockMetaData';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.qrl.BlockMetaData.repeatedFields_ = [4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qrl.BlockMetaData.prototype.toObject = function(opt_includeInstance) {
  return proto.qrl.BlockMetaData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qrl.BlockMetaData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.BlockMetaData.toObject = function(includeInstance, msg) {
  var f, obj = {
    isOrphan: jspb.Message.getFieldWithDefault(msg, 1, false),
    blockDifficulty: msg.getBlockDifficulty_asB64(),
    cumulativeDifficulty: msg.getCumulativeDifficulty_asB64(),
    childHeaderhashesList: msg.getChildHeaderhashesList_asB64(),
    lastNHeaderhashesList: msg.getLastNHeaderhashesList_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qrl.BlockMetaData}
 */
proto.qrl.BlockMetaData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qrl.BlockMetaData;
  return proto.qrl.BlockMetaData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qrl.BlockMetaData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qrl.BlockMetaData}
 */
proto.qrl.BlockMetaData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsOrphan(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBlockDifficulty(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setCumulativeDifficulty(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addChildHeaderhashes(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addLastNHeaderhashes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qrl.BlockMetaData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qrl.BlockMetaData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qrl.BlockMetaData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.BlockMetaData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIsOrphan();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getBlockDifficulty_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getCumulativeDifficulty_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getChildHeaderhashesList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      4,
      f
    );
  }
  f = message.getLastNHeaderhashesList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      5,
      f
    );
  }
};


/**
 * optional bool is_orphan = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.qrl.BlockMetaData.prototype.getIsOrphan = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.qrl.BlockMetaData.prototype.setIsOrphan = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bytes block_difficulty = 2;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.BlockMetaData.prototype.getBlockDifficulty = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes block_difficulty = 2;
 * This is a type-conversion wrapper around `getBlockDifficulty()`
 * @return {string}
 */
proto.qrl.BlockMetaData.prototype.getBlockDifficulty_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBlockDifficulty()));
};


/**
 * optional bytes block_difficulty = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBlockDifficulty()`
 * @return {!Uint8Array}
 */
proto.qrl.BlockMetaData.prototype.getBlockDifficulty_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBlockDifficulty()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.BlockMetaData.prototype.setBlockDifficulty = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes cumulative_difficulty = 3;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.BlockMetaData.prototype.getCumulativeDifficulty = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes cumulative_difficulty = 3;
 * This is a type-conversion wrapper around `getCumulativeDifficulty()`
 * @return {string}
 */
proto.qrl.BlockMetaData.prototype.getCumulativeDifficulty_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getCumulativeDifficulty()));
};


/**
 * optional bytes cumulative_difficulty = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getCumulativeDifficulty()`
 * @return {!Uint8Array}
 */
proto.qrl.BlockMetaData.prototype.getCumulativeDifficulty_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getCumulativeDifficulty()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.BlockMetaData.prototype.setCumulativeDifficulty = function(value) {
  jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * repeated bytes child_headerhashes = 4;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.qrl.BlockMetaData.prototype.getChildHeaderhashesList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * repeated bytes child_headerhashes = 4;
 * This is a type-conversion wrapper around `getChildHeaderhashesList()`
 * @return {!Array.<string>}
 */
proto.qrl.BlockMetaData.prototype.getChildHeaderhashesList_asB64 = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.bytesListAsB64(
      this.getChildHeaderhashesList()));
};


/**
 * repeated bytes child_headerhashes = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getChildHeaderhashesList()`
 * @return {!Array.<!Uint8Array>}
 */
proto.qrl.BlockMetaData.prototype.getChildHeaderhashesList_asU8 = function() {
  return /** @type {!Array.<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getChildHeaderhashesList()));
};


/** @param {!(Array<!Uint8Array>|Array<string>)} value */
proto.qrl.BlockMetaData.prototype.setChildHeaderhashesList = function(value) {
  jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 */
proto.qrl.BlockMetaData.prototype.addChildHeaderhashes = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


proto.qrl.BlockMetaData.prototype.clearChildHeaderhashesList = function() {
  this.setChildHeaderhashesList([]);
};


/**
 * repeated bytes last_N_headerhashes = 5;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.qrl.BlockMetaData.prototype.getLastNHeaderhashesList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * repeated bytes last_N_headerhashes = 5;
 * This is a type-conversion wrapper around `getLastNHeaderhashesList()`
 * @return {!Array.<string>}
 */
proto.qrl.BlockMetaData.prototype.getLastNHeaderhashesList_asB64 = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.bytesListAsB64(
      this.getLastNHeaderhashesList()));
};


/**
 * repeated bytes last_N_headerhashes = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getLastNHeaderhashesList()`
 * @return {!Array.<!Uint8Array>}
 */
proto.qrl.BlockMetaData.prototype.getLastNHeaderhashesList_asU8 = function() {
  return /** @type {!Array.<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getLastNHeaderhashesList()));
};


/** @param {!(Array<!Uint8Array>|Array<string>)} value */
proto.qrl.BlockMetaData.prototype.setLastNHeaderhashesList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 */
proto.qrl.BlockMetaData.prototype.addLastNHeaderhashes = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


proto.qrl.BlockMetaData.prototype.clearLastNHeaderhashesList = function() {
  this.setLastNHeaderhashesList([]);
};


