/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.qrl.BlockHeader');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qrl.BlockHeader = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.qrl.BlockHeader, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qrl.BlockHeader.displayName = 'proto.qrl.BlockHeader';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qrl.BlockHeader.prototype.toObject = function(opt_includeInstance) {
  return proto.qrl.BlockHeader.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qrl.BlockHeader} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.BlockHeader.toObject = function(includeInstance, msg) {
  var f, obj = {
    hashHeader: msg.getHashHeader_asB64(),
    blockNumber: jspb.Message.getFieldWithDefault(msg, 2, 0),
    timestampSeconds: jspb.Message.getFieldWithDefault(msg, 3, 0),
    hashHeaderPrev: msg.getHashHeaderPrev_asB64(),
    rewardBlock: jspb.Message.getFieldWithDefault(msg, 5, 0),
    rewardFee: jspb.Message.getFieldWithDefault(msg, 6, 0),
    merkleRoot: msg.getMerkleRoot_asB64(),
    pk: msg.getPk_asB64(),
    miningNonce: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qrl.BlockHeader}
 */
proto.qrl.BlockHeader.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qrl.BlockHeader;
  return proto.qrl.BlockHeader.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qrl.BlockHeader} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qrl.BlockHeader}
 */
proto.qrl.BlockHeader.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setHashHeader(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setBlockNumber(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestampSeconds(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setHashHeaderPrev(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRewardBlock(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRewardFee(value);
      break;
    case 7:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setMerkleRoot(value);
      break;
    case 8:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPk(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMiningNonce(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qrl.BlockHeader.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qrl.BlockHeader.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qrl.BlockHeader} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.BlockHeader.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHashHeader_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getBlockNumber();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getTimestampSeconds();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getHashHeaderPrev_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getRewardBlock();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getRewardFee();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getMerkleRoot_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      7,
      f
    );
  }
  f = message.getPk_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      8,
      f
    );
  }
  f = message.getMiningNonce();
  if (f !== 0) {
    writer.writeUint64(
      9,
      f
    );
  }
};


/**
 * optional bytes hash_header = 1;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.BlockHeader.prototype.getHashHeader = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes hash_header = 1;
 * This is a type-conversion wrapper around `getHashHeader()`
 * @return {string}
 */
proto.qrl.BlockHeader.prototype.getHashHeader_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getHashHeader()));
};


/**
 * optional bytes hash_header = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getHashHeader()`
 * @return {!Uint8Array}
 */
proto.qrl.BlockHeader.prototype.getHashHeader_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getHashHeader()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.BlockHeader.prototype.setHashHeader = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional uint64 block_number = 2;
 * @return {number}
 */
proto.qrl.BlockHeader.prototype.getBlockNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.qrl.BlockHeader.prototype.setBlockNumber = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 timestamp_seconds = 3;
 * @return {number}
 */
proto.qrl.BlockHeader.prototype.getTimestampSeconds = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.qrl.BlockHeader.prototype.setTimestampSeconds = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bytes hash_header_prev = 4;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.BlockHeader.prototype.getHashHeaderPrev = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes hash_header_prev = 4;
 * This is a type-conversion wrapper around `getHashHeaderPrev()`
 * @return {string}
 */
proto.qrl.BlockHeader.prototype.getHashHeaderPrev_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getHashHeaderPrev()));
};


/**
 * optional bytes hash_header_prev = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getHashHeaderPrev()`
 * @return {!Uint8Array}
 */
proto.qrl.BlockHeader.prototype.getHashHeaderPrev_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getHashHeaderPrev()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.BlockHeader.prototype.setHashHeaderPrev = function(value) {
  jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional uint64 reward_block = 5;
 * @return {number}
 */
proto.qrl.BlockHeader.prototype.getRewardBlock = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.qrl.BlockHeader.prototype.setRewardBlock = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint64 reward_fee = 6;
 * @return {number}
 */
proto.qrl.BlockHeader.prototype.getRewardFee = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.qrl.BlockHeader.prototype.setRewardFee = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional bytes merkle_root = 7;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.BlockHeader.prototype.getMerkleRoot = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * optional bytes merkle_root = 7;
 * This is a type-conversion wrapper around `getMerkleRoot()`
 * @return {string}
 */
proto.qrl.BlockHeader.prototype.getMerkleRoot_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getMerkleRoot()));
};


/**
 * optional bytes merkle_root = 7;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getMerkleRoot()`
 * @return {!Uint8Array}
 */
proto.qrl.BlockHeader.prototype.getMerkleRoot_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getMerkleRoot()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.BlockHeader.prototype.setMerkleRoot = function(value) {
  jspb.Message.setProto3BytesField(this, 7, value);
};


/**
 * optional bytes PK = 8;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.BlockHeader.prototype.getPk = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * optional bytes PK = 8;
 * This is a type-conversion wrapper around `getPk()`
 * @return {string}
 */
proto.qrl.BlockHeader.prototype.getPk_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPk()));
};


/**
 * optional bytes PK = 8;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPk()`
 * @return {!Uint8Array}
 */
proto.qrl.BlockHeader.prototype.getPk_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPk()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.BlockHeader.prototype.setPk = function(value) {
  jspb.Message.setProto3BytesField(this, 8, value);
};


/**
 * optional uint64 mining_nonce = 9;
 * @return {number}
 */
proto.qrl.BlockHeader.prototype.getMiningNonce = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.qrl.BlockHeader.prototype.setMiningNonce = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


