/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.qrl.Block');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.qrl.BlockHeader');
goog.require('proto.qrl.GenesisBalance');
goog.require('proto.qrl.Transaction');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qrl.Block = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.qrl.Block.repeatedFields_, null);
};
goog.inherits(proto.qrl.Block, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qrl.Block.displayName = 'proto.qrl.Block';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.qrl.Block.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qrl.Block.prototype.toObject = function(opt_includeInstance) {
  return proto.qrl.Block.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qrl.Block} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.Block.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && proto.qrl.BlockHeader.toObject(includeInstance, f),
    transactionsList: jspb.Message.toObjectList(msg.getTransactionsList(),
    proto.qrl.Transaction.toObject, includeInstance),
    genesisBalanceList: jspb.Message.toObjectList(msg.getGenesisBalanceList(),
    proto.qrl.GenesisBalance.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qrl.Block}
 */
proto.qrl.Block.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qrl.Block;
  return proto.qrl.Block.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qrl.Block} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qrl.Block}
 */
proto.qrl.Block.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.qrl.BlockHeader;
      reader.readMessage(value,proto.qrl.BlockHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new proto.qrl.Transaction;
      reader.readMessage(value,proto.qrl.Transaction.deserializeBinaryFromReader);
      msg.addTransactions(value);
      break;
    case 3:
      var value = new proto.qrl.GenesisBalance;
      reader.readMessage(value,proto.qrl.GenesisBalance.deserializeBinaryFromReader);
      msg.addGenesisBalance(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qrl.Block.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qrl.Block.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qrl.Block} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.Block.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.qrl.BlockHeader.serializeBinaryToWriter
    );
  }
  f = message.getTransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.qrl.Transaction.serializeBinaryToWriter
    );
  }
  f = message.getGenesisBalanceList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.qrl.GenesisBalance.serializeBinaryToWriter
    );
  }
};


/**
 * optional BlockHeader header = 1;
 * @return {?proto.qrl.BlockHeader}
 */
proto.qrl.Block.prototype.getHeader = function() {
  return /** @type{?proto.qrl.BlockHeader} */ (
    jspb.Message.getWrapperField(this, proto.qrl.BlockHeader, 1));
};


/** @param {?proto.qrl.BlockHeader|undefined} value */
proto.qrl.Block.prototype.setHeader = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.qrl.Block.prototype.clearHeader = function() {
  this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qrl.Block.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Transaction transactions = 2;
 * @return {!Array.<!proto.qrl.Transaction>}
 */
proto.qrl.Block.prototype.getTransactionsList = function() {
  return /** @type{!Array.<!proto.qrl.Transaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.qrl.Transaction, 2));
};


/** @param {!Array.<!proto.qrl.Transaction>} value */
proto.qrl.Block.prototype.setTransactionsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.qrl.Transaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.qrl.Transaction}
 */
proto.qrl.Block.prototype.addTransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.qrl.Transaction, opt_index);
};


proto.qrl.Block.prototype.clearTransactionsList = function() {
  this.setTransactionsList([]);
};


/**
 * repeated GenesisBalance genesis_balance = 3;
 * @return {!Array.<!proto.qrl.GenesisBalance>}
 */
proto.qrl.Block.prototype.getGenesisBalanceList = function() {
  return /** @type{!Array.<!proto.qrl.GenesisBalance>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.qrl.GenesisBalance, 3));
};


/** @param {!Array.<!proto.qrl.GenesisBalance>} value */
proto.qrl.Block.prototype.setGenesisBalanceList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.qrl.GenesisBalance=} opt_value
 * @param {number=} opt_index
 * @return {!proto.qrl.GenesisBalance}
 */
proto.qrl.Block.prototype.addGenesisBalance = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.qrl.GenesisBalance, opt_index);
};


proto.qrl.Block.prototype.clearGenesisBalanceList = function() {
  this.setGenesisBalanceList([]);
};


