/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.qrl.BlockDataPoint');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qrl.BlockDataPoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.qrl.BlockDataPoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qrl.BlockDataPoint.displayName = 'proto.qrl.BlockDataPoint';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qrl.BlockDataPoint.prototype.toObject = function(opt_includeInstance) {
  return proto.qrl.BlockDataPoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qrl.BlockDataPoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.BlockDataPoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    number: jspb.Message.getFieldWithDefault(msg, 1, 0),
    difficulty: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 3, 0),
    timeLast: jspb.Message.getFieldWithDefault(msg, 4, 0),
    timeMovavg: jspb.Message.getFieldWithDefault(msg, 5, 0),
    hashPower: +jspb.Message.getFieldWithDefault(msg, 6, 0.0),
    headerHash: msg.getHeaderHash_asB64(),
    headerHashPrev: msg.getHeaderHashPrev_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qrl.BlockDataPoint}
 */
proto.qrl.BlockDataPoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qrl.BlockDataPoint;
  return proto.qrl.BlockDataPoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qrl.BlockDataPoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qrl.BlockDataPoint}
 */
proto.qrl.BlockDataPoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setNumber(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDifficulty(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimeLast(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimeMovavg(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setHashPower(value);
      break;
    case 7:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setHeaderHash(value);
      break;
    case 8:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setHeaderHashPrev(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qrl.BlockDataPoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qrl.BlockDataPoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qrl.BlockDataPoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.BlockDataPoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNumber();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getDifficulty();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getTimeLast();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getTimeMovavg();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getHashPower();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getHeaderHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      7,
      f
    );
  }
  f = message.getHeaderHashPrev_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      8,
      f
    );
  }
};


/**
 * optional uint64 number = 1;
 * @return {number}
 */
proto.qrl.BlockDataPoint.prototype.getNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.qrl.BlockDataPoint.prototype.setNumber = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string difficulty = 2;
 * @return {string}
 */
proto.qrl.BlockDataPoint.prototype.getDifficulty = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.qrl.BlockDataPoint.prototype.setDifficulty = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint64 timestamp = 3;
 * @return {number}
 */
proto.qrl.BlockDataPoint.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.qrl.BlockDataPoint.prototype.setTimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint64 time_last = 4;
 * @return {number}
 */
proto.qrl.BlockDataPoint.prototype.getTimeLast = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.qrl.BlockDataPoint.prototype.setTimeLast = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint64 time_movavg = 5;
 * @return {number}
 */
proto.qrl.BlockDataPoint.prototype.getTimeMovavg = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.qrl.BlockDataPoint.prototype.setTimeMovavg = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional float hash_power = 6;
 * @return {number}
 */
proto.qrl.BlockDataPoint.prototype.getHashPower = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 6, 0.0));
};


/** @param {number} value */
proto.qrl.BlockDataPoint.prototype.setHashPower = function(value) {
  jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional bytes header_hash = 7;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.BlockDataPoint.prototype.getHeaderHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * optional bytes header_hash = 7;
 * This is a type-conversion wrapper around `getHeaderHash()`
 * @return {string}
 */
proto.qrl.BlockDataPoint.prototype.getHeaderHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getHeaderHash()));
};


/**
 * optional bytes header_hash = 7;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getHeaderHash()`
 * @return {!Uint8Array}
 */
proto.qrl.BlockDataPoint.prototype.getHeaderHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getHeaderHash()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.BlockDataPoint.prototype.setHeaderHash = function(value) {
  jspb.Message.setProto3BytesField(this, 7, value);
};


/**
 * optional bytes header_hash_prev = 8;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.BlockDataPoint.prototype.getHeaderHashPrev = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * optional bytes header_hash_prev = 8;
 * This is a type-conversion wrapper around `getHeaderHashPrev()`
 * @return {string}
 */
proto.qrl.BlockDataPoint.prototype.getHeaderHashPrev_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getHeaderHashPrev()));
};


/**
 * optional bytes header_hash_prev = 8;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getHeaderHashPrev()`
 * @return {!Uint8Array}
 */
proto.qrl.BlockDataPoint.prototype.getHeaderHashPrev_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getHeaderHashPrev()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.BlockDataPoint.prototype.setHeaderHashPrev = function(value) {
  jspb.Message.setProto3BytesField(this, 8, value);
};


