/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.qrl.EncryptedEphemeralMessage');
goog.provide('proto.qrl.EncryptedEphemeralMessage.Channel');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qrl.EncryptedEphemeralMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.qrl.EncryptedEphemeralMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qrl.EncryptedEphemeralMessage.displayName = 'proto.qrl.EncryptedEphemeralMessage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qrl.EncryptedEphemeralMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.qrl.EncryptedEphemeralMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qrl.EncryptedEphemeralMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.EncryptedEphemeralMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    msgId: msg.getMsgId_asB64(),
    ttl: jspb.Message.getFieldWithDefault(msg, 2, 0),
    ttr: jspb.Message.getFieldWithDefault(msg, 3, 0),
    channel: (f = msg.getChannel()) && proto.qrl.EncryptedEphemeralMessage.Channel.toObject(includeInstance, f),
    nonce: jspb.Message.getFieldWithDefault(msg, 6, 0),
    payload: msg.getPayload_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qrl.EncryptedEphemeralMessage}
 */
proto.qrl.EncryptedEphemeralMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qrl.EncryptedEphemeralMessage;
  return proto.qrl.EncryptedEphemeralMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qrl.EncryptedEphemeralMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qrl.EncryptedEphemeralMessage}
 */
proto.qrl.EncryptedEphemeralMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setMsgId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTtl(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTtr(value);
      break;
    case 5:
      var value = new proto.qrl.EncryptedEphemeralMessage.Channel;
      reader.readMessage(value,proto.qrl.EncryptedEphemeralMessage.Channel.deserializeBinaryFromReader);
      msg.setChannel(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setNonce(value);
      break;
    case 7:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPayload(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qrl.EncryptedEphemeralMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qrl.EncryptedEphemeralMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qrl.EncryptedEphemeralMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.EncryptedEphemeralMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMsgId_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getTtl();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getTtr();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getChannel();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.qrl.EncryptedEphemeralMessage.Channel.serializeBinaryToWriter
    );
  }
  f = message.getNonce();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getPayload_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      7,
      f
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qrl.EncryptedEphemeralMessage.Channel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.qrl.EncryptedEphemeralMessage.Channel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qrl.EncryptedEphemeralMessage.Channel.displayName = 'proto.qrl.EncryptedEphemeralMessage.Channel';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qrl.EncryptedEphemeralMessage.Channel.prototype.toObject = function(opt_includeInstance) {
  return proto.qrl.EncryptedEphemeralMessage.Channel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qrl.EncryptedEphemeralMessage.Channel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.EncryptedEphemeralMessage.Channel.toObject = function(includeInstance, msg) {
  var f, obj = {
    encAes256Symkey: msg.getEncAes256Symkey_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qrl.EncryptedEphemeralMessage.Channel}
 */
proto.qrl.EncryptedEphemeralMessage.Channel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qrl.EncryptedEphemeralMessage.Channel;
  return proto.qrl.EncryptedEphemeralMessage.Channel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qrl.EncryptedEphemeralMessage.Channel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qrl.EncryptedEphemeralMessage.Channel}
 */
proto.qrl.EncryptedEphemeralMessage.Channel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEncAes256Symkey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qrl.EncryptedEphemeralMessage.Channel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qrl.EncryptedEphemeralMessage.Channel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qrl.EncryptedEphemeralMessage.Channel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.EncryptedEphemeralMessage.Channel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEncAes256Symkey_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
};


/**
 * optional bytes enc_aes256_symkey = 4;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.EncryptedEphemeralMessage.Channel.prototype.getEncAes256Symkey = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes enc_aes256_symkey = 4;
 * This is a type-conversion wrapper around `getEncAes256Symkey()`
 * @return {string}
 */
proto.qrl.EncryptedEphemeralMessage.Channel.prototype.getEncAes256Symkey_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEncAes256Symkey()));
};


/**
 * optional bytes enc_aes256_symkey = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEncAes256Symkey()`
 * @return {!Uint8Array}
 */
proto.qrl.EncryptedEphemeralMessage.Channel.prototype.getEncAes256Symkey_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEncAes256Symkey()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.EncryptedEphemeralMessage.Channel.prototype.setEncAes256Symkey = function(value) {
  jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional bytes msg_id = 1;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.EncryptedEphemeralMessage.prototype.getMsgId = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes msg_id = 1;
 * This is a type-conversion wrapper around `getMsgId()`
 * @return {string}
 */
proto.qrl.EncryptedEphemeralMessage.prototype.getMsgId_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getMsgId()));
};


/**
 * optional bytes msg_id = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getMsgId()`
 * @return {!Uint8Array}
 */
proto.qrl.EncryptedEphemeralMessage.prototype.getMsgId_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getMsgId()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.EncryptedEphemeralMessage.prototype.setMsgId = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional uint64 ttl = 2;
 * @return {number}
 */
proto.qrl.EncryptedEphemeralMessage.prototype.getTtl = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.qrl.EncryptedEphemeralMessage.prototype.setTtl = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 ttr = 3;
 * @return {number}
 */
proto.qrl.EncryptedEphemeralMessage.prototype.getTtr = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.qrl.EncryptedEphemeralMessage.prototype.setTtr = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional Channel channel = 5;
 * @return {?proto.qrl.EncryptedEphemeralMessage.Channel}
 */
proto.qrl.EncryptedEphemeralMessage.prototype.getChannel = function() {
  return /** @type{?proto.qrl.EncryptedEphemeralMessage.Channel} */ (
    jspb.Message.getWrapperField(this, proto.qrl.EncryptedEphemeralMessage.Channel, 5));
};


/** @param {?proto.qrl.EncryptedEphemeralMessage.Channel|undefined} value */
proto.qrl.EncryptedEphemeralMessage.prototype.setChannel = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.qrl.EncryptedEphemeralMessage.prototype.clearChannel = function() {
  this.setChannel(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qrl.EncryptedEphemeralMessage.prototype.hasChannel = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional uint64 nonce = 6;
 * @return {number}
 */
proto.qrl.EncryptedEphemeralMessage.prototype.getNonce = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.qrl.EncryptedEphemeralMessage.prototype.setNonce = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional bytes payload = 7;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.EncryptedEphemeralMessage.prototype.getPayload = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * optional bytes payload = 7;
 * This is a type-conversion wrapper around `getPayload()`
 * @return {string}
 */
proto.qrl.EncryptedEphemeralMessage.prototype.getPayload_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPayload()));
};


/**
 * optional bytes payload = 7;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPayload()`
 * @return {!Uint8Array}
 */
proto.qrl.EncryptedEphemeralMessage.prototype.getPayload_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPayload()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.EncryptedEphemeralMessage.prototype.setPayload = function(value) {
  jspb.Message.setProto3BytesField(this, 7, value);
};


