/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.qrl.EphemeralMetadata');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.qrl.EncryptedEphemeralMessage');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qrl.EphemeralMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.qrl.EphemeralMetadata.repeatedFields_, null);
};
goog.inherits(proto.qrl.EphemeralMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qrl.EphemeralMetadata.displayName = 'proto.qrl.EphemeralMetadata';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.qrl.EphemeralMetadata.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qrl.EphemeralMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.qrl.EphemeralMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qrl.EphemeralMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.EphemeralMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    encryptedEphemeralMessageListList: jspb.Message.toObjectList(msg.getEncryptedEphemeralMessageListList(),
    proto.qrl.EncryptedEphemeralMessage.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qrl.EphemeralMetadata}
 */
proto.qrl.EphemeralMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qrl.EphemeralMetadata;
  return proto.qrl.EphemeralMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qrl.EphemeralMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qrl.EphemeralMetadata}
 */
proto.qrl.EphemeralMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new proto.qrl.EncryptedEphemeralMessage;
      reader.readMessage(value,proto.qrl.EncryptedEphemeralMessage.deserializeBinaryFromReader);
      msg.addEncryptedEphemeralMessageList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qrl.EphemeralMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qrl.EphemeralMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qrl.EphemeralMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.EphemeralMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEncryptedEphemeralMessageListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.qrl.EncryptedEphemeralMessage.serializeBinaryToWriter
    );
  }
};


/**
 * repeated EncryptedEphemeralMessage encrypted_ephemeral_message_list = 2;
 * @return {!Array.<!proto.qrl.EncryptedEphemeralMessage>}
 */
proto.qrl.EphemeralMetadata.prototype.getEncryptedEphemeralMessageListList = function() {
  return /** @type{!Array.<!proto.qrl.EncryptedEphemeralMessage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.qrl.EncryptedEphemeralMessage, 2));
};


/** @param {!Array.<!proto.qrl.EncryptedEphemeralMessage>} value */
proto.qrl.EphemeralMetadata.prototype.setEncryptedEphemeralMessageListList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.qrl.EncryptedEphemeralMessage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.qrl.EncryptedEphemeralMessage}
 */
proto.qrl.EphemeralMetadata.prototype.addEncryptedEphemeralMessageList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.qrl.EncryptedEphemeralMessage, opt_index);
};


proto.qrl.EphemeralMetadata.prototype.clearEncryptedEphemeralMessageListList = function() {
  this.setEncryptedEphemeralMessageListList([]);
};


