/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.qrl.GetBlockReq');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qrl.GetBlockReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.qrl.GetBlockReq.oneofGroups_);
};
goog.inherits(proto.qrl.GetBlockReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qrl.GetBlockReq.displayName = 'proto.qrl.GetBlockReq';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.qrl.GetBlockReq.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.qrl.GetBlockReq.QueryCase = {
  QUERY_NOT_SET: 0,
  INDEX: 1,
  AFTER_HASH: 2
};

/**
 * @return {proto.qrl.GetBlockReq.QueryCase}
 */
proto.qrl.GetBlockReq.prototype.getQueryCase = function() {
  return /** @type {proto.qrl.GetBlockReq.QueryCase} */(jspb.Message.computeOneofCase(this, proto.qrl.GetBlockReq.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qrl.GetBlockReq.prototype.toObject = function(opt_includeInstance) {
  return proto.qrl.GetBlockReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qrl.GetBlockReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.GetBlockReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    index: jspb.Message.getFieldWithDefault(msg, 1, 0),
    afterHash: msg.getAfterHash_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qrl.GetBlockReq}
 */
proto.qrl.GetBlockReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qrl.GetBlockReq;
  return proto.qrl.GetBlockReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qrl.GetBlockReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qrl.GetBlockReq}
 */
proto.qrl.GetBlockReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setIndex(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAfterHash(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qrl.GetBlockReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qrl.GetBlockReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qrl.GetBlockReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.GetBlockReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional uint64 index = 1;
 * @return {number}
 */
proto.qrl.GetBlockReq.prototype.getIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.qrl.GetBlockReq.prototype.setIndex = function(value) {
  jspb.Message.setOneofField(this, 1, proto.qrl.GetBlockReq.oneofGroups_[0], value);
};


proto.qrl.GetBlockReq.prototype.clearIndex = function() {
  jspb.Message.setOneofField(this, 1, proto.qrl.GetBlockReq.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qrl.GetBlockReq.prototype.hasIndex = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes after_hash = 2;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.GetBlockReq.prototype.getAfterHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes after_hash = 2;
 * This is a type-conversion wrapper around `getAfterHash()`
 * @return {string}
 */
proto.qrl.GetBlockReq.prototype.getAfterHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAfterHash()));
};


/**
 * optional bytes after_hash = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAfterHash()`
 * @return {!Uint8Array}
 */
proto.qrl.GetBlockReq.prototype.getAfterHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAfterHash()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.GetBlockReq.prototype.setAfterHash = function(value) {
  jspb.Message.setOneofField(this, 2, proto.qrl.GetBlockReq.oneofGroups_[0], value);
};


proto.qrl.GetBlockReq.prototype.clearAfterHash = function() {
  jspb.Message.setOneofField(this, 2, proto.qrl.GetBlockReq.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qrl.GetBlockReq.prototype.hasAfterHash = function() {
  return jspb.Message.getField(this, 2) != null;
};


