/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.qrl.GetLatestDataResp');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.qrl.BlockHeaderExtended');
goog.require('proto.qrl.TransactionExtended');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qrl.GetLatestDataResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.qrl.GetLatestDataResp.repeatedFields_, null);
};
goog.inherits(proto.qrl.GetLatestDataResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qrl.GetLatestDataResp.displayName = 'proto.qrl.GetLatestDataResp';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.qrl.GetLatestDataResp.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qrl.GetLatestDataResp.prototype.toObject = function(opt_includeInstance) {
  return proto.qrl.GetLatestDataResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qrl.GetLatestDataResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.GetLatestDataResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    blockheadersList: jspb.Message.toObjectList(msg.getBlockheadersList(),
    proto.qrl.BlockHeaderExtended.toObject, includeInstance),
    transactionsList: jspb.Message.toObjectList(msg.getTransactionsList(),
    proto.qrl.TransactionExtended.toObject, includeInstance),
    transactionsUnconfirmedList: jspb.Message.toObjectList(msg.getTransactionsUnconfirmedList(),
    proto.qrl.TransactionExtended.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qrl.GetLatestDataResp}
 */
proto.qrl.GetLatestDataResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qrl.GetLatestDataResp;
  return proto.qrl.GetLatestDataResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qrl.GetLatestDataResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qrl.GetLatestDataResp}
 */
proto.qrl.GetLatestDataResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.qrl.BlockHeaderExtended;
      reader.readMessage(value,proto.qrl.BlockHeaderExtended.deserializeBinaryFromReader);
      msg.addBlockheaders(value);
      break;
    case 2:
      var value = new proto.qrl.TransactionExtended;
      reader.readMessage(value,proto.qrl.TransactionExtended.deserializeBinaryFromReader);
      msg.addTransactions(value);
      break;
    case 3:
      var value = new proto.qrl.TransactionExtended;
      reader.readMessage(value,proto.qrl.TransactionExtended.deserializeBinaryFromReader);
      msg.addTransactionsUnconfirmed(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qrl.GetLatestDataResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qrl.GetLatestDataResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qrl.GetLatestDataResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.GetLatestDataResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBlockheadersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.qrl.BlockHeaderExtended.serializeBinaryToWriter
    );
  }
  f = message.getTransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.qrl.TransactionExtended.serializeBinaryToWriter
    );
  }
  f = message.getTransactionsUnconfirmedList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.qrl.TransactionExtended.serializeBinaryToWriter
    );
  }
};


/**
 * repeated BlockHeaderExtended blockheaders = 1;
 * @return {!Array.<!proto.qrl.BlockHeaderExtended>}
 */
proto.qrl.GetLatestDataResp.prototype.getBlockheadersList = function() {
  return /** @type{!Array.<!proto.qrl.BlockHeaderExtended>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.qrl.BlockHeaderExtended, 1));
};


/** @param {!Array.<!proto.qrl.BlockHeaderExtended>} value */
proto.qrl.GetLatestDataResp.prototype.setBlockheadersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.qrl.BlockHeaderExtended=} opt_value
 * @param {number=} opt_index
 * @return {!proto.qrl.BlockHeaderExtended}
 */
proto.qrl.GetLatestDataResp.prototype.addBlockheaders = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.qrl.BlockHeaderExtended, opt_index);
};


proto.qrl.GetLatestDataResp.prototype.clearBlockheadersList = function() {
  this.setBlockheadersList([]);
};


/**
 * repeated TransactionExtended transactions = 2;
 * @return {!Array.<!proto.qrl.TransactionExtended>}
 */
proto.qrl.GetLatestDataResp.prototype.getTransactionsList = function() {
  return /** @type{!Array.<!proto.qrl.TransactionExtended>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.qrl.TransactionExtended, 2));
};


/** @param {!Array.<!proto.qrl.TransactionExtended>} value */
proto.qrl.GetLatestDataResp.prototype.setTransactionsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.qrl.TransactionExtended=} opt_value
 * @param {number=} opt_index
 * @return {!proto.qrl.TransactionExtended}
 */
proto.qrl.GetLatestDataResp.prototype.addTransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.qrl.TransactionExtended, opt_index);
};


proto.qrl.GetLatestDataResp.prototype.clearTransactionsList = function() {
  this.setTransactionsList([]);
};


/**
 * repeated TransactionExtended transactions_unconfirmed = 3;
 * @return {!Array.<!proto.qrl.TransactionExtended>}
 */
proto.qrl.GetLatestDataResp.prototype.getTransactionsUnconfirmedList = function() {
  return /** @type{!Array.<!proto.qrl.TransactionExtended>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.qrl.TransactionExtended, 3));
};


/** @param {!Array.<!proto.qrl.TransactionExtended>} value */
proto.qrl.GetLatestDataResp.prototype.setTransactionsUnconfirmedList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.qrl.TransactionExtended=} opt_value
 * @param {number=} opt_index
 * @return {!proto.qrl.TransactionExtended}
 */
proto.qrl.GetLatestDataResp.prototype.addTransactionsUnconfirmed = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.qrl.TransactionExtended, opt_index);
};


proto.qrl.GetLatestDataResp.prototype.clearTransactionsUnconfirmedList = function() {
  this.setTransactionsUnconfirmedList([]);
};


