/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.qrl.NodeInfo');
goog.provide('proto.qrl.NodeInfo.State');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qrl.NodeInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.qrl.NodeInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qrl.NodeInfo.displayName = 'proto.qrl.NodeInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qrl.NodeInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.qrl.NodeInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qrl.NodeInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.NodeInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, ""),
    state: jspb.Message.getFieldWithDefault(msg, 2, 0),
    numConnections: jspb.Message.getFieldWithDefault(msg, 3, 0),
    numKnownPeers: jspb.Message.getFieldWithDefault(msg, 4, 0),
    uptime: jspb.Message.getFieldWithDefault(msg, 5, 0),
    blockHeight: jspb.Message.getFieldWithDefault(msg, 6, 0),
    blockLastHash: msg.getBlockLastHash_asB64(),
    networkId: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qrl.NodeInfo}
 */
proto.qrl.NodeInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qrl.NodeInfo;
  return proto.qrl.NodeInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qrl.NodeInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qrl.NodeInfo}
 */
proto.qrl.NodeInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 2:
      var value = /** @type {!proto.qrl.NodeInfo.State} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNumConnections(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNumKnownPeers(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setUptime(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setBlockHeight(value);
      break;
    case 7:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBlockLastHash(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setNetworkId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qrl.NodeInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qrl.NodeInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qrl.NodeInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.NodeInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getNumConnections();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getNumKnownPeers();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getUptime();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getBlockHeight();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getBlockLastHash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      7,
      f
    );
  }
  f = message.getNetworkId();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.qrl.NodeInfo.State = {
  UNKNOWN: 0,
  UNSYNCED: 1,
  SYNCING: 2,
  SYNCED: 3,
  FORKED: 4
};

/**
 * optional string version = 1;
 * @return {string}
 */
proto.qrl.NodeInfo.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.qrl.NodeInfo.prototype.setVersion = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional State state = 2;
 * @return {!proto.qrl.NodeInfo.State}
 */
proto.qrl.NodeInfo.prototype.getState = function() {
  return /** @type {!proto.qrl.NodeInfo.State} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.qrl.NodeInfo.State} value */
proto.qrl.NodeInfo.prototype.setState = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional uint32 num_connections = 3;
 * @return {number}
 */
proto.qrl.NodeInfo.prototype.getNumConnections = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.qrl.NodeInfo.prototype.setNumConnections = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 num_known_peers = 4;
 * @return {number}
 */
proto.qrl.NodeInfo.prototype.getNumKnownPeers = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.qrl.NodeInfo.prototype.setNumKnownPeers = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint64 uptime = 5;
 * @return {number}
 */
proto.qrl.NodeInfo.prototype.getUptime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.qrl.NodeInfo.prototype.setUptime = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint64 block_height = 6;
 * @return {number}
 */
proto.qrl.NodeInfo.prototype.getBlockHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.qrl.NodeInfo.prototype.setBlockHeight = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional bytes block_last_hash = 7;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.NodeInfo.prototype.getBlockLastHash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * optional bytes block_last_hash = 7;
 * This is a type-conversion wrapper around `getBlockLastHash()`
 * @return {string}
 */
proto.qrl.NodeInfo.prototype.getBlockLastHash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBlockLastHash()));
};


/**
 * optional bytes block_last_hash = 7;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBlockLastHash()`
 * @return {!Uint8Array}
 */
proto.qrl.NodeInfo.prototype.getBlockLastHash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBlockLastHash()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.NodeInfo.prototype.setBlockLastHash = function(value) {
  jspb.Message.setProto3BytesField(this, 7, value);
};


/**
 * optional string network_id = 8;
 * @return {string}
 */
proto.qrl.NodeInfo.prototype.getNetworkId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.qrl.NodeInfo.prototype.setNetworkId = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


