/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.qrl.SlaveTxnReq');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qrl.SlaveTxnReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.qrl.SlaveTxnReq.repeatedFields_, null);
};
goog.inherits(proto.qrl.SlaveTxnReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qrl.SlaveTxnReq.displayName = 'proto.qrl.SlaveTxnReq';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.qrl.SlaveTxnReq.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qrl.SlaveTxnReq.prototype.toObject = function(opt_includeInstance) {
  return proto.qrl.SlaveTxnReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qrl.SlaveTxnReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.SlaveTxnReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    addressFrom: msg.getAddressFrom_asB64(),
    slavePksList: msg.getSlavePksList_asB64(),
    accessTypesList: jspb.Message.getRepeatedField(msg, 3),
    fee: jspb.Message.getFieldWithDefault(msg, 4, 0),
    xmssPk: msg.getXmssPk_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qrl.SlaveTxnReq}
 */
proto.qrl.SlaveTxnReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qrl.SlaveTxnReq;
  return proto.qrl.SlaveTxnReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qrl.SlaveTxnReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qrl.SlaveTxnReq}
 */
proto.qrl.SlaveTxnReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAddressFrom(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addSlavePks(value);
      break;
    case 3:
      var value = /** @type {!Array.<number>} */ (reader.readPackedUint32());
      msg.setAccessTypesList(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFee(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setXmssPk(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qrl.SlaveTxnReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qrl.SlaveTxnReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qrl.SlaveTxnReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.SlaveTxnReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddressFrom_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getSlavePksList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      2,
      f
    );
  }
  f = message.getAccessTypesList();
  if (f.length > 0) {
    writer.writePackedUint32(
      3,
      f
    );
  }
  f = message.getFee();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getXmssPk_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
};


/**
 * optional bytes address_from = 1;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.SlaveTxnReq.prototype.getAddressFrom = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes address_from = 1;
 * This is a type-conversion wrapper around `getAddressFrom()`
 * @return {string}
 */
proto.qrl.SlaveTxnReq.prototype.getAddressFrom_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAddressFrom()));
};


/**
 * optional bytes address_from = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAddressFrom()`
 * @return {!Uint8Array}
 */
proto.qrl.SlaveTxnReq.prototype.getAddressFrom_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAddressFrom()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.SlaveTxnReq.prototype.setAddressFrom = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * repeated bytes slave_pks = 2;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.qrl.SlaveTxnReq.prototype.getSlavePksList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * repeated bytes slave_pks = 2;
 * This is a type-conversion wrapper around `getSlavePksList()`
 * @return {!Array.<string>}
 */
proto.qrl.SlaveTxnReq.prototype.getSlavePksList_asB64 = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.bytesListAsB64(
      this.getSlavePksList()));
};


/**
 * repeated bytes slave_pks = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSlavePksList()`
 * @return {!Array.<!Uint8Array>}
 */
proto.qrl.SlaveTxnReq.prototype.getSlavePksList_asU8 = function() {
  return /** @type {!Array.<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getSlavePksList()));
};


/** @param {!(Array<!Uint8Array>|Array<string>)} value */
proto.qrl.SlaveTxnReq.prototype.setSlavePksList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 */
proto.qrl.SlaveTxnReq.prototype.addSlavePks = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.qrl.SlaveTxnReq.prototype.clearSlavePksList = function() {
  this.setSlavePksList([]);
};


/**
 * repeated uint32 access_types = 3;
 * @return {!Array.<number>}
 */
proto.qrl.SlaveTxnReq.prototype.getAccessTypesList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array.<number>} value */
proto.qrl.SlaveTxnReq.prototype.setAccessTypesList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.qrl.SlaveTxnReq.prototype.addAccessTypes = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.qrl.SlaveTxnReq.prototype.clearAccessTypesList = function() {
  this.setAccessTypesList([]);
};


/**
 * optional uint64 fee = 4;
 * @return {number}
 */
proto.qrl.SlaveTxnReq.prototype.getFee = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.qrl.SlaveTxnReq.prototype.setFee = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional bytes xmss_pk = 5;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.SlaveTxnReq.prototype.getXmssPk = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes xmss_pk = 5;
 * This is a type-conversion wrapper around `getXmssPk()`
 * @return {string}
 */
proto.qrl.SlaveTxnReq.prototype.getXmssPk_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getXmssPk()));
};


/**
 * optional bytes xmss_pk = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getXmssPk()`
 * @return {!Uint8Array}
 */
proto.qrl.SlaveTxnReq.prototype.getXmssPk_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getXmssPk()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.SlaveTxnReq.prototype.setXmssPk = function(value) {
  jspb.Message.setProto3BytesField(this, 5, value);
};


