/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.qrl.StateLoader');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qrl.StateLoader = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.qrl.StateLoader.repeatedFields_, null);
};
goog.inherits(proto.qrl.StateLoader, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qrl.StateLoader.displayName = 'proto.qrl.StateLoader';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.qrl.StateLoader.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qrl.StateLoader.prototype.toObject = function(opt_includeInstance) {
  return proto.qrl.StateLoader.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qrl.StateLoader} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.StateLoader.toObject = function(includeInstance, msg) {
  var f, obj = {
    addressesList: msg.getAddressesList_asB64(),
    tokenTxhashList: msg.getTokenTxhashList_asB64(),
    txhashList: msg.getTxhashList_asB64(),
    totalCoinSupply: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qrl.StateLoader}
 */
proto.qrl.StateLoader.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qrl.StateLoader;
  return proto.qrl.StateLoader.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qrl.StateLoader} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qrl.StateLoader}
 */
proto.qrl.StateLoader.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addAddresses(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addTokenTxhash(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addTxhash(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTotalCoinSupply(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qrl.StateLoader.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qrl.StateLoader.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qrl.StateLoader} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.StateLoader.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddressesList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      1,
      f
    );
  }
  f = message.getTokenTxhashList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      2,
      f
    );
  }
  f = message.getTxhashList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      3,
      f
    );
  }
  f = message.getTotalCoinSupply();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
};


/**
 * repeated bytes addresses = 1;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.qrl.StateLoader.prototype.getAddressesList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * repeated bytes addresses = 1;
 * This is a type-conversion wrapper around `getAddressesList()`
 * @return {!Array.<string>}
 */
proto.qrl.StateLoader.prototype.getAddressesList_asB64 = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.bytesListAsB64(
      this.getAddressesList()));
};


/**
 * repeated bytes addresses = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAddressesList()`
 * @return {!Array.<!Uint8Array>}
 */
proto.qrl.StateLoader.prototype.getAddressesList_asU8 = function() {
  return /** @type {!Array.<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getAddressesList()));
};


/** @param {!(Array<!Uint8Array>|Array<string>)} value */
proto.qrl.StateLoader.prototype.setAddressesList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 */
proto.qrl.StateLoader.prototype.addAddresses = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.qrl.StateLoader.prototype.clearAddressesList = function() {
  this.setAddressesList([]);
};


/**
 * repeated bytes token_txhash = 2;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.qrl.StateLoader.prototype.getTokenTxhashList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * repeated bytes token_txhash = 2;
 * This is a type-conversion wrapper around `getTokenTxhashList()`
 * @return {!Array.<string>}
 */
proto.qrl.StateLoader.prototype.getTokenTxhashList_asB64 = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.bytesListAsB64(
      this.getTokenTxhashList()));
};


/**
 * repeated bytes token_txhash = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTokenTxhashList()`
 * @return {!Array.<!Uint8Array>}
 */
proto.qrl.StateLoader.prototype.getTokenTxhashList_asU8 = function() {
  return /** @type {!Array.<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getTokenTxhashList()));
};


/** @param {!(Array<!Uint8Array>|Array<string>)} value */
proto.qrl.StateLoader.prototype.setTokenTxhashList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 */
proto.qrl.StateLoader.prototype.addTokenTxhash = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.qrl.StateLoader.prototype.clearTokenTxhashList = function() {
  this.setTokenTxhashList([]);
};


/**
 * repeated bytes txhash = 3;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.qrl.StateLoader.prototype.getTxhashList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * repeated bytes txhash = 3;
 * This is a type-conversion wrapper around `getTxhashList()`
 * @return {!Array.<string>}
 */
proto.qrl.StateLoader.prototype.getTxhashList_asB64 = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.bytesListAsB64(
      this.getTxhashList()));
};


/**
 * repeated bytes txhash = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTxhashList()`
 * @return {!Array.<!Uint8Array>}
 */
proto.qrl.StateLoader.prototype.getTxhashList_asU8 = function() {
  return /** @type {!Array.<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getTxhashList()));
};


/** @param {!(Array<!Uint8Array>|Array<string>)} value */
proto.qrl.StateLoader.prototype.setTxhashList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 */
proto.qrl.StateLoader.prototype.addTxhash = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.qrl.StateLoader.prototype.clearTxhashList = function() {
  this.setTxhashList([]);
};


/**
 * optional uint64 total_coin_supply = 4;
 * @return {number}
 */
proto.qrl.StateLoader.prototype.getTotalCoinSupply = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.qrl.StateLoader.prototype.setTotalCoinSupply = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


