/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.qrl.TokenMetadata');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qrl.TokenMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.qrl.TokenMetadata.repeatedFields_, null);
};
goog.inherits(proto.qrl.TokenMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qrl.TokenMetadata.displayName = 'proto.qrl.TokenMetadata';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.qrl.TokenMetadata.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qrl.TokenMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.qrl.TokenMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qrl.TokenMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.TokenMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    tokenTxhash: msg.getTokenTxhash_asB64(),
    transferTokenTxHashesList: msg.getTransferTokenTxHashesList_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qrl.TokenMetadata}
 */
proto.qrl.TokenMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qrl.TokenMetadata;
  return proto.qrl.TokenMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qrl.TokenMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qrl.TokenMetadata}
 */
proto.qrl.TokenMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTokenTxhash(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addTransferTokenTxHashes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qrl.TokenMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qrl.TokenMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qrl.TokenMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.TokenMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTokenTxhash_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getTransferTokenTxHashesList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      2,
      f
    );
  }
};


/**
 * optional bytes token_txhash = 1;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.TokenMetadata.prototype.getTokenTxhash = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes token_txhash = 1;
 * This is a type-conversion wrapper around `getTokenTxhash()`
 * @return {string}
 */
proto.qrl.TokenMetadata.prototype.getTokenTxhash_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTokenTxhash()));
};


/**
 * optional bytes token_txhash = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTokenTxhash()`
 * @return {!Uint8Array}
 */
proto.qrl.TokenMetadata.prototype.getTokenTxhash_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTokenTxhash()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.TokenMetadata.prototype.setTokenTxhash = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * repeated bytes transfer_token_tx_hashes = 2;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.qrl.TokenMetadata.prototype.getTransferTokenTxHashesList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * repeated bytes transfer_token_tx_hashes = 2;
 * This is a type-conversion wrapper around `getTransferTokenTxHashesList()`
 * @return {!Array.<string>}
 */
proto.qrl.TokenMetadata.prototype.getTransferTokenTxHashesList_asB64 = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.bytesListAsB64(
      this.getTransferTokenTxHashesList()));
};


/**
 * repeated bytes transfer_token_tx_hashes = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTransferTokenTxHashesList()`
 * @return {!Array.<!Uint8Array>}
 */
proto.qrl.TokenMetadata.prototype.getTransferTokenTxHashesList_asU8 = function() {
  return /** @type {!Array.<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getTransferTokenTxHashesList()));
};


/** @param {!(Array<!Uint8Array>|Array<string>)} value */
proto.qrl.TokenMetadata.prototype.setTransferTokenTxHashesList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 */
proto.qrl.TokenMetadata.prototype.addTransferTokenTxHashes = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.qrl.TokenMetadata.prototype.clearTransferTokenTxHashesList = function() {
  this.setTransferTokenTxHashesList([]);
};


