/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.qrl.TokenTxnReq');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.qrl.AddressAmount');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qrl.TokenTxnReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.qrl.TokenTxnReq.repeatedFields_, null);
};
goog.inherits(proto.qrl.TokenTxnReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qrl.TokenTxnReq.displayName = 'proto.qrl.TokenTxnReq';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.qrl.TokenTxnReq.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qrl.TokenTxnReq.prototype.toObject = function(opt_includeInstance) {
  return proto.qrl.TokenTxnReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qrl.TokenTxnReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.TokenTxnReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    addressFrom: msg.getAddressFrom_asB64(),
    symbol: msg.getSymbol_asB64(),
    name: msg.getName_asB64(),
    owner: msg.getOwner_asB64(),
    decimals: jspb.Message.getFieldWithDefault(msg, 5, 0),
    initialBalancesList: jspb.Message.toObjectList(msg.getInitialBalancesList(),
    proto.qrl.AddressAmount.toObject, includeInstance),
    fee: jspb.Message.getFieldWithDefault(msg, 7, 0),
    xmssPk: msg.getXmssPk_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qrl.TokenTxnReq}
 */
proto.qrl.TokenTxnReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qrl.TokenTxnReq;
  return proto.qrl.TokenTxnReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qrl.TokenTxnReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qrl.TokenTxnReq}
 */
proto.qrl.TokenTxnReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAddressFrom(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSymbol(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setOwner(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDecimals(value);
      break;
    case 6:
      var value = new proto.qrl.AddressAmount;
      reader.readMessage(value,proto.qrl.AddressAmount.deserializeBinaryFromReader);
      msg.addInitialBalances(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFee(value);
      break;
    case 8:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setXmssPk(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qrl.TokenTxnReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qrl.TokenTxnReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qrl.TokenTxnReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qrl.TokenTxnReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddressFrom_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getSymbol_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getName_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getOwner_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getDecimals();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getInitialBalancesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.qrl.AddressAmount.serializeBinaryToWriter
    );
  }
  f = message.getFee();
  if (f !== 0) {
    writer.writeUint64(
      7,
      f
    );
  }
  f = message.getXmssPk_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      8,
      f
    );
  }
};


/**
 * optional bytes address_from = 1;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.TokenTxnReq.prototype.getAddressFrom = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes address_from = 1;
 * This is a type-conversion wrapper around `getAddressFrom()`
 * @return {string}
 */
proto.qrl.TokenTxnReq.prototype.getAddressFrom_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAddressFrom()));
};


/**
 * optional bytes address_from = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAddressFrom()`
 * @return {!Uint8Array}
 */
proto.qrl.TokenTxnReq.prototype.getAddressFrom_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAddressFrom()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.TokenTxnReq.prototype.setAddressFrom = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes symbol = 2;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.TokenTxnReq.prototype.getSymbol = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes symbol = 2;
 * This is a type-conversion wrapper around `getSymbol()`
 * @return {string}
 */
proto.qrl.TokenTxnReq.prototype.getSymbol_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSymbol()));
};


/**
 * optional bytes symbol = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSymbol()`
 * @return {!Uint8Array}
 */
proto.qrl.TokenTxnReq.prototype.getSymbol_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSymbol()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.TokenTxnReq.prototype.setSymbol = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes name = 3;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.TokenTxnReq.prototype.getName = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes name = 3;
 * This is a type-conversion wrapper around `getName()`
 * @return {string}
 */
proto.qrl.TokenTxnReq.prototype.getName_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getName()));
};


/**
 * optional bytes name = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getName()`
 * @return {!Uint8Array}
 */
proto.qrl.TokenTxnReq.prototype.getName_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getName()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.TokenTxnReq.prototype.setName = function(value) {
  jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional bytes owner = 4;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.TokenTxnReq.prototype.getOwner = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes owner = 4;
 * This is a type-conversion wrapper around `getOwner()`
 * @return {string}
 */
proto.qrl.TokenTxnReq.prototype.getOwner_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getOwner()));
};


/**
 * optional bytes owner = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getOwner()`
 * @return {!Uint8Array}
 */
proto.qrl.TokenTxnReq.prototype.getOwner_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getOwner()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.TokenTxnReq.prototype.setOwner = function(value) {
  jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional uint64 decimals = 5;
 * @return {number}
 */
proto.qrl.TokenTxnReq.prototype.getDecimals = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.qrl.TokenTxnReq.prototype.setDecimals = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * repeated AddressAmount initial_balances = 6;
 * @return {!Array.<!proto.qrl.AddressAmount>}
 */
proto.qrl.TokenTxnReq.prototype.getInitialBalancesList = function() {
  return /** @type{!Array.<!proto.qrl.AddressAmount>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.qrl.AddressAmount, 6));
};


/** @param {!Array.<!proto.qrl.AddressAmount>} value */
proto.qrl.TokenTxnReq.prototype.setInitialBalancesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.qrl.AddressAmount=} opt_value
 * @param {number=} opt_index
 * @return {!proto.qrl.AddressAmount}
 */
proto.qrl.TokenTxnReq.prototype.addInitialBalances = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.qrl.AddressAmount, opt_index);
};


proto.qrl.TokenTxnReq.prototype.clearInitialBalancesList = function() {
  this.setInitialBalancesList([]);
};


/**
 * optional uint64 fee = 7;
 * @return {number}
 */
proto.qrl.TokenTxnReq.prototype.getFee = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.qrl.TokenTxnReq.prototype.setFee = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional bytes xmss_pk = 8;
 * @return {!(string|Uint8Array)}
 */
proto.qrl.TokenTxnReq.prototype.getXmssPk = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * optional bytes xmss_pk = 8;
 * This is a type-conversion wrapper around `getXmssPk()`
 * @return {string}
 */
proto.qrl.TokenTxnReq.prototype.getXmssPk_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getXmssPk()));
};


/**
 * optional bytes xmss_pk = 8;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getXmssPk()`
 * @return {!Uint8Array}
 */
proto.qrl.TokenTxnReq.prototype.getXmssPk_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getXmssPk()));
};


/** @param {!(string|Uint8Array)} value */
proto.qrl.TokenTxnReq.prototype.setXmssPk = function(value) {
  jspb.Message.setProto3BytesField(this, 8, value);
};


