/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnisample_JNIHelloWorld_JNIActivity */

#ifndef _Included_com_theqrl_AndroidWalletModule
#define _Included_com_theqrl_AndroidWalletModule

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_theqrl_AndroidWalletModule_androidWalletJNI(JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif

#endif